services:
    postgres:
      image: postgres:latest
      env_file: .env
      ports:
        - "${DB_PORT}:${DB_PORT}"
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - ./_shared/pgdata:/var/lib/postgresql/data

